# Generated by Django 4.2.11 on 2026-02-08 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "__first__"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenants",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="tenantdocument",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_documents",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="tenantdocument",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_documents",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["organization", "email"], name="tenants_ten_organiz_af7ed0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantdocument",
            index=models.Index(
                fields=["organization", "tenant"], name="tenants_ten_organiz_2fa679_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantdocument",
            index=models.Index(
                fields=["organization", "document_type"],
                name="tenants_ten_organiz_48f56e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                fields=("organization", "email"), name="unique_email_per_organization"
            ),
        ),
    ]
