# Generated by Django 4.2.11 on 2026-02-08 22:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="JM", max_length=2)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizations/logos/"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="America/Jamaica", max_length=50),
                ),
                ("currency", models.CharField(default="JMD", max_length=3)),
                ("subscription_plan", models.CharField(default="free", max_length=20)),
                ("subscription_active", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment Building"),
                            ("house", "Single Family Home"),
                            ("condo", "Condominium"),
                            ("townhouse", "Townhouse"),
                            ("commercial", "Commercial"),
                            ("mixed", "Mixed Use"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="JM", max_length=2)),
                ("units_count", models.IntegerField(default=1)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("parking_spaces", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("manager", "Property Manager"),
                            ("staff", "Staff"),
                            ("viewer", "Viewer"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("can_manage_tenants", models.BooleanField(default=True)),
                ("can_manage_finances", models.BooleanField(default=False)),
                ("can_manage_properties", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "role"],
                "unique_together": {("user", "organization")},
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(
                related_name="organizations",
                through="organizations.OrganizationMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.CharField(max_length=50)),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("bedrooms", models.IntegerField(default=1)),
                (
                    "bathrooms",
                    models.DecimalField(decimal_places=1, default=1, max_digits=3),
                ),
                ("square_feet", models.IntegerField(blank=True, null=True)),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="organizations.property",
                    ),
                ),
            ],
            options={
                "ordering": ["property", "unit_number"],
                "unique_together": {("property", "unit_number")},
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["slug"], name="organizatio_slug_048085_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["email"], name="organizatio_email_5622e6_idx"),
        ),
    ]
