import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/ui/status-badge";
import { Download } from "lucide-react";
import { useParams } from "react-router-dom";

function formatCurrency(amount: number): string {
  return `J$${amount.toLocaleString()}`;
}

// Mock receipt data
const mockReceipt = {
  receiptNumber: "RCP-2026-0201",
  date: "February 1, 2026, 2:34 PM",
  from: {
    name: "Johnson Properties Ltd",
    address: "123 Main Street, Kingston",
  },
  to: {
    name: "Marcus Brown",
    unit: "Unit 1A",
  },
  description: "Monthly Rent — Unit 1A",
  amount: 45000,
  method: "Bank Transfer",
};

export default function Receipt() {
  const { id } = useParams();

  // Simulate checking receipt validity
  const isValidReceipt = id && id.length > 3;

  if (!isValidReceipt) {
    return (
      <div className="min-h-screen bg-background-secondary flex items-center justify-center p-4">
        <div className="w-full max-w-lg bg-card border border-border rounded-lg p-6 text-center">
          <p className="text-sm text-muted-foreground">
            Receipt not found. Please check the link or contact your landlord.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background-secondary flex items-center justify-center p-4">
      <div className="w-full max-w-lg bg-card border border-border rounded-lg overflow-hidden">
        {/* Header with Download */}
        <div className="p-6 flex items-start justify-between">
          <div>
            <p className="text-xs uppercase tracking-wider text-muted-foreground mb-1">
              RECEIPT
            </p>
            <p className="text-sm font-semibold text-foreground">{mockReceipt.receiptNumber}</p>
            <p className="text-xs text-muted-foreground">{mockReceipt.date}</p>
          </div>
          <Button variant="outline" size="sm">
            <Download className="h-4 w-4" />
            Download PDF
          </Button>
        </div>

        <div className="border-t border-border" />

        {/* From / To */}
        <div className="p-6 grid grid-cols-2 gap-6">
          <div>
            <p className="text-xs uppercase tracking-wider text-muted-foreground mb-2">From</p>
            <p className="text-sm font-medium text-foreground">{mockReceipt.from.name}</p>
            <p className="text-xs text-muted-foreground">{mockReceipt.from.address}</p>
          </div>
          <div>
            <p className="text-xs uppercase tracking-wider text-muted-foreground mb-2">To</p>
            <p className="text-sm font-medium text-foreground">{mockReceipt.to.name}</p>
            <p className="text-xs text-muted-foreground">{mockReceipt.to.unit}</p>
          </div>
        </div>

        <div className="border-t border-border" />

        {/* Payment Details */}
        <div className="p-6">
          <div className="space-y-3">
            <div className="flex justify-between">
              <span className="text-sm text-muted-foreground">Description</span>
              <span className="text-sm text-foreground">{mockReceipt.description}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-sm text-muted-foreground">Amount</span>
              <span className="text-sm font-medium text-foreground">
                {formatCurrency(mockReceipt.amount)}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-sm text-muted-foreground">Payment Method</span>
              <span className="text-sm text-foreground">{mockReceipt.method}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-sm text-muted-foreground">Status</span>
              <StatusBadge variant="paid">Paid</StatusBadge>
            </div>
          </div>
        </div>

        <div className="border-t border-border" />

        {/* Total */}
        <div className="p-6 flex justify-between items-center">
          <span className="text-base font-semibold text-foreground">Total Paid</span>
          <span className="text-base font-semibold text-foreground">
            {formatCurrency(mockReceipt.amount)}
          </span>
        </div>

        {/* Footer */}
        <div className="px-6 pb-6">
          <p className="text-xs text-muted-foreground text-center">
            This receipt was automatically generated by RentCollect
          </p>
        </div>
      </div>
    </div>
  );
}
