# Generated by Django 4.2.11 on 2026-02-08 22:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "__first__"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="paymentreminder",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_reminders",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(db_index=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "tenant"], name="payments_in_organiz_4ef566_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization", "tenant"], name="payments_pa_organiz_6f3f7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization", "status"], name="payments_pa_organiz_1d83a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreminder",
            index=models.Index(
                fields=["organization", "tenant"], name="payments_pa_organiz_b094ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreminder",
            index=models.Index(
                fields=["organization", "sent_date"],
                name="payments_pa_organiz_540a51_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("organization", "invoice_number"),
                name="unique_invoice_number_per_organization",
            ),
        ),
    ]
