# Generated by Django 4.2.11 on 2026-02-08 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documents.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0002_tenant_organization_tenantdocument_organization_and_more"),
        ("organizations", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(upload_to=documents.models.document_upload_path),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("file_type", models.CharField(max_length=50)),
                (
                    "document_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date of the document",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="When this document expires", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_signed", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signature_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-document_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("lease", "Lease Agreement"),
                            ("id", "Identification"),
                            ("payment", "Payment Receipt"),
                            ("notice", "Notice"),
                            ("maintenance", "Maintenance"),
                            ("insurance", "Insurance"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_categories",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Document Categories",
            },
        ),
        migrations.CreateModel(
            name="DocumentSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signature_image",
                    models.TextField(help_text="Base64 encoded signature image"),
                ),
                ("signed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=True)),
                ("verification_code", models.CharField(blank=True, max_length=100)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_signatures",
                        to="organizations.organization",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-signed_at"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.documentcategory",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Template content with variables like {{tenant_name}}, {{unit}}, etc."
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict,
                        help_text="List of variables available in this template",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.documentcategory",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_templates",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "name"],
                        name="documents_d_organiz_29d226_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_template_per_organization"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsignature",
            index=models.Index(
                fields=["organization", "document"],
                name="documents_d_organiz_bd4150_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentsignature",
            index=models.Index(
                fields=["organization", "signed_at"],
                name="documents_d_organiz_550d64_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentsignature",
            unique_together={("document", "signer")},
        ),
        migrations.AddIndex(
            model_name="documentcategory",
            index=models.Index(
                fields=["organization", "name"], name="documents_d_organiz_372422_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentcategory",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_category_per_organization"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "category"], name="documents_d_tenant__e26847_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["expiry_date"], name="documents_d_expiry__1d702a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "tenant"], name="documents_d_organiz_97b528_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "category"],
                name="documents_d_organiz_54de96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "expiry_date"],
                name="documents_d_organiz_c97890_idx",
            ),
        ),
    ]
